Tile peptides
ssarkizova/hlathenav2 pull request #17
Opened 2024-03-07 20:54 UTC by benfl-dfci

Add a tile peptides function to create a peptide dataset from a fasta file, using all peptides of specified lengths.

I set the allowed lengths to be between 8 and 12 because I think that's what we talked about, but I'm not sure if those are the exact numbers we talked about.

This doesn't handle spaces in the fasta file. Let me know if that should be included.

2024-03-08 03:51 UTC, ssarkizova commented on hlathena/peptide_dataset.py
> +                for start in range(0, len(record) - length + 1)]
Great to see the fast input being worked in!! A few suggestions here - when we tile peptides from a fasta file it is typically handy to keep some metadata for each peptide so once we have a prediction report (or other analysis) we can related them back to the input sequences. For example some useful columns to create along each peptide sequence are:
   the record name (or identifier)
   the start [end] position of the peptide
   the length of the peptide
   anything else?

Thanks much!

2024-03-08 14:55 UTC, benfl-dfci commented on hlathena/peptide_dataset.py
> +                for start in range(0, len(record) - length + 1)]
I added record_id, start_pos, length columns to the dataframe. Please let me know if there are more things I should add (I excluded end since it can be calculated from start and length) or if I should change the names of the columns. I'm not sure how they were named in v1.

2024-03-08 22:21 UTC, ssarkizova commented on hlathena/peptide_dataset.py
> +                for start in range(0, len(record) - length + 1)]
Awesome, thank you!

2024-03-13 23:03 UTC, cleo-dfci requested changes
Just a couple thoughts

2024-04-02 15:21 UTC, cleo-dfci approved these changes

2024-04-02 15:21 UTC, merged